resolver: lts-6.17

packages:
- '.'
- location:
    git: git@github.com:openbrainsrc/obutils
    commit: e3e766b83efc44a8fce631410505ab1664a572f2 
- location:
    git: git@github.com:openbrainsrc/postgresql-simple-sop.git
    commit: eb5ce7037d3044659ff30677af43e5e1ec1f56ce

extra-deps:
# - carray-0.1.5.2
- daemons-0.2.1
- parallel-io-0.3.3
- AC-Angle-1.0
- basic-sop-0.1.0.5
- bindings-svm-0.2.1
- easyplot-1.0
- http-test-0.2.4
- iso3166-country-codes-0.20140203.7
- json-sop-0.1.0.4
- lazysmallcheck-0.6
- multiset-0.3.0
- optional-args-1.0.0
- pooled-io-0.0.2
- postgresql-simple-sop-0.1.0.7
- pretty-sop-0.1.0.1
- reverse-geocoding-0.2.1
- storable-tuple-0.0.2
- concurrent-split-0.0.0.1
- ix-shapable-0.1.0
- lens-sop-0.1.0.2
- storable-record-0.0.3
- unsafe-0.0
- utility-ht-0.0.11
- aeson-better-errors-0.9.0.9
- protocol-buffers-2.1.3
- protocol-buffers-descriptor-2.1.3
- language-lua-0.6.3.2
- gnuplot-0.5.3.1
- data-accessor-transformers-0.2.1.6
- mime-0.3.4
